### ISSUE TITLE
Idea Karma

### ISSUE THREAD

**Issue by wannabeCitizen** [wannabeCitizen/projectsystem#8]
In the UI, a user should be able to give karma to an idea version.

**Comment by murrayju** [comment]
I'm thinking that each version has a thumbs up/down button, and the user can choose one, the other, or neither. We can then compute the total karma of each version as the sum of all the +/-1 that each user assigned, and then sort the versions by this value.

@wannabeCitizen Does that jive with what you are thinking, and/or what is implemented in the api?

**Comment by wannabeCitizen** [comment]
I think that sounds great!  I think that we had originally said that each
person only gets to give + karma to 1 version.

Are you straying from that or are you thinking you can give karma to every
version?

(Also, sorry I'm not on here actively right now, but I have to prep for
class to start.  I'm going to plan some weekly time to devote to this again
this semester.  Slightly different than before as I want to plan some raw
work time rather than just our meeting).

**Comment by murrayju** [comment]
I'm not sure what I'm saying. I like the reddit model, where you can give each thing either +1 or -1. I could see an idea having 5 version, and want to say that 2 are very good, and 1 is very bad. I think getting more data will help us to more accurately sort the list (when there are lots of versions).

The single vote per idea model could work too.
